### ISSUE TITLE
Deployment fails if Apex class does not already exist

### ISSUE THREAD

**Issue by mitchnimbly** [jdcrensh/create-react-app#19]
### Is this a bug report?

Yes

### Did you try recovering your dependencies?

Yup!

### Which terms did you search for in User Guide?

😬
### Environment

(paste the output of the command here)

### Steps to Reproduce

1. Create a new project and deploy it to Salesforce (the controller and Visualforce page shouldn't exist yet)
1. Fill out the .local.env with your Salesforce sandbox creds
1. run `yarn build && yarn deploy`

### Expected Behavior

The deployment should succeed. All green checks.

### Actual Behavior

I received the following error however the Apex class SalesPortalController was created. When I ran `yarn deploy` again, the deployment succeeded.

```
$ yarn deploy
yarn run v1.5.1
$ react-scripts deploy

✔ Logging in as xxx@gonimbly.com.yyy
✔ Bundling build assets as static resource
✔ Deploying bundle as SalesPortal.resource
✔ Checking for SalesPortalController

TypeError: this._createSingle is not a function
    at Tooling.Connection.insert.Connection.create (/Users/mitchconquer/Projects/sales-portal/node_modules/jsforce/lib/connection.js:728:12)
    at module.exports.SObject.insert.SObject.create (/Users/mitchconquer/Projects/sales-portal/node_modules/jsforce/lib/sobject.js:62:21)
    at conn.tooling.sobject.findOne.then.then.res (/Users/mitchconquer/Projects/sales-portal/node_modules/salesforce-react-scripts/scripts/deploy.js:155:10)
    at tryCallOne (/Users/mitchconquer/Projects/sales-portal/node_modules/jsforce/node_modules/promise/lib/core.js:37:12)
    at /Users/mitchconquer/Projects/sales-portal/node_modules/jsforce/node_modules/promise/lib/core.js:123:15
    at flush (/Users/mitchconquer/Projects/sales-portal/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c react-scripts deploy
Directory: /Users/mitchconquer/Projects/sales-portal
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/mitchconquer/Projects/sales-portal/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by jdcrensh** [comment]
Resolved in v3.1.2-0
